/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GreenEnergyCornerRouteImport } from './routes/green-energy-corner'
import { Route as StarterKitsRouteImport } from './routes/starter-kits'
import { Route as TechnologyRouteImport } from './routes/technology'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GreenEnergyCornerRoute = GreenEnergyCornerRouteImport.update({
  id: '/green-energy-corner',
  path: '/green-energy-corner',
  getParentRoute: () => rootRouteImport,
} as any)
const StarterKitsRoute = StarterKitsRouteImport.update({
  id: '/starter-kits',
  path: '/starter-kits',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/green-energy-corner': typeof GreenEnergyCornerRoute
  '/starter-kits': typeof StarterKitsRoute
  '/technology': typeof TechnologyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/green-energy-corner': typeof GreenEnergyCornerRoute
  '/starter-kits': typeof StarterKitsRoute
  '/technology': typeof TechnologyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/green-energy-corner': typeof GreenEnergyCornerRoute
  '/starter-kits': typeof StarterKitsRoute
  '/technology': typeof TechnologyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/green-energy-corner' | '/starter-kits' | '/technology'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/green-energy-corner' | '/starter-kits' | '/technology'
  id:
    '__root__' | '/' | '/green-energy-corner' | '/starter-kits' | '/technology'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GreenEnergyCornerRoute: typeof GreenEnergyCornerRoute
  StarterKitsRoute: typeof StarterKitsRoute
  TechnologyRoute: typeof TechnologyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/green-energy-corner': {
      id: '/green-energy-corner'
      path: '/green-energy-corner'
      fullPath: '/green-energy-corner'
      preLoaderRoute: typeof GreenEnergyCornerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starter-kits': {
      id: '/starter-kits'
      path: '/starter-kits'
      fullPath: '/starter-kits'
      preLoaderRoute: typeof StarterKitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GreenEnergyCornerRoute: GreenEnergyCornerRoute,
  StarterKitsRoute: StarterKitsRoute,
  TechnologyRoute: TechnologyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
